- name: Install Java on Ansible-Management
  hosts: 13.127.194.85
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install default JDK
      apt:
        name: default-jdk
        state: present